# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
    - master
    paths:
      - '**.sml'
      - 'Holmakefile'
  pull_request:
    branches:
    - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ubuntu:latest
    # Set environment variables
    env:
      HOLDIR: ${{ github.workspace }}/HOL
      CAKEMLDIR: ${{ github.workspace }}/cakeml
      CAKEDIR: ${{ github.workspace }}/cakeml # Remove this once issue #20 is resolved
      LD_LIBRARY_PATH: /usr/local/lib:$LD_LIBRARY_PATH
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Update PATH
      run: |
        echo "$HOLDIR/bin" >> $GITHUB_PATH
    - name: Get build-essentials
      run: |
        apt update
        apt install -y build-essential gcc-10 libffi-dev
    - name: Checkout Poly/ML
      uses: actions/checkout@v2
      with:
        repository: polyml/polyml
        ref: fixes-5.9
        path: polyml
    - name: Build Poly/ML
      run: |
        cd polyml
        ./configure
        make
        make install
    - name: Checkout HOL4
      uses: actions/checkout@v2
      with:
        repository: HOL-Theorem-Prover/HOL
        ref: master
        path: HOL
    - name: Checkout pure
      uses: actions/checkout@v2
      with:
        path: pure
    - name: Checkout CakeML
      uses: actions/checkout@v2
      with:
        repository: CakeML/CakeML
        path: cakeml
    - name: Build HOL4
      run: |
        cd $HOLDIR
        poly < tools/smart-configure.sml
        bin/build
    - name: Build CakeML misc
      run: |
        cd $CAKEMLDIR/misc
        Holmake
    - name: Build CakeML semantics
      run: |
        cd $CAKEMLDIR/semantics
        Holmake
    - name: Build CakeML semantics/proofs
      run: |
        cd $CAKEMLDIR/semantics/proofs
        Holmake
    - name: Build CakeML semantics/alt_semantics
      run: |
        cd $CAKEMLDIR/semantics/alt_semantics
        Holmake
    - name: Build CakeML semantics/alt_semantics/proofs
      run: |
        cd $CAKEMLDIR/semantics/alt_semantics/proofs
        Holmake
    - name: Build CakeML basis/pure
      run: |
        cd $CAKEMLDIR/basis/pure
        Holmake
    - name: Build misc
      run: |
        cd pure/misc
        Holmake
    - name: Build language
      run: |
        cd pure/language
        Holmake
    - name: Build meta-theory
      run: |
        cd pure/meta-theory
        Holmake
    - name: Build compiler/backend
      run: |
        cd pure/compiler/backend
        Holmake
    - name: Build compiler/backend/languages
      run: |
        cd pure/compiler/backend/languages
        Holmake
    - name: Build compiler/backend/languages/semantics
      run: |
        cd pure/compiler/backend/languages/semantics
        Holmake
    - name: Build compiler/backend/languages/properties
      run: |
        cd pure/compiler/backend/languages/properties
        Holmake
    - name: Build typing
      run: |
        cd pure/typing
        Holmake
    - name: Build compiler/backend/passes
      run: |
        cd pure/compiler/backend/passes
        Holmake
    - name: Build compiler/backend/passes/proofs
      run: |
        cd pure/compiler/backend/passes/proofs
        Holmake
    - name: Build compiler/parsing
      run: |
        cd pure/compiler/parsing
        Holmake
    - name: Build compiler
      run: |
        cd pure/compiler
        Holmake
    - name: Build examples
      run: |
        cd pure/examples
        Holmake
    - name: Translate compiler
      run: |
        cd pure/compiler/binary
        Holmake
