# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    paths:
      - '**.sml'
      - 'Holmakefile'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: cakeml/hol4:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout pure
      uses: actions/checkout@v2
      with:
        path: pure
    - name: Checkout CakeML
      uses: actions/checkout@v2
      with:
        repository: CakeML/CakeML
        path: cakeml
    - name: Build misc
      run: |
        cd pure/misc
        Holmake
    - name: Build language
      run: |
        cd pure/language
        Holmake
    - name: Build typing
      run: |
        cd pure/typing
        Holmake
    - name: Build meta-theory
      run: |
        cd pure/meta-theory
        Holmake
    - name: Build compiler/backend
      run: |
        cd pure/compiler/backend
        Holmake
    - name: Build compiler/backend/proofs
      run: |
        cd pure/compiler/backend/proofs
        Holmake 
    - name: Build compiler
      run: |
        cd pure/compiler
        Holmake
    - name: Build compiler/binary
      run: |
        cd pure/compiler/binary
        Holmake
    - name: Build examples
      run: |
        cd pure/examples
        Holmake
    - name: Build cakeml-semantics
      run: |
        cd pure/cakeml-semantics
        Holmake
